// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countConnectionsByUser = `-- name: CountConnectionsByUser :one
SELECT count(*)
FROM connections
WHERE user_id = $1
`

// Dashboard counter. Every status counts: a disconnected number is still a
// number the user connected, and hiding it would make the total fall when a
// customer is trying to work out what went wrong.
func (q *Queries) CountConnectionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingConnectionForAccount = `-- name: DeletePendingConnectionForAccount :execrows
DELETE FROM connections
WHERE user_id = $1
  AND messaging_account_id = $2
  AND phone_number_id IS NULL
`

type DeletePendingConnectionForAccountParams struct {
	UserID             uuid.UUID `json:"user_id"`
	MessagingAccountID string    `json:"messaging_account_id"`
}

// Drops the placeholder row for an account that has just gained a number.
//
// Without this the customer would see both "Needs a number" and the number they
// just connected for the same business account, and the placeholder would keep
// claiming a token that nothing uses.
func (q *Queries) DeletePendingConnectionForAccount(ctx context.Context, arg DeletePendingConnectionForAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingConnectionForAccount, arg.UserID, arg.MessagingAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disconnectOwnedConnectionAndPauseCampaigns = `-- name: DisconnectOwnedConnectionAndPauseCampaigns :one
WITH target AS (
    UPDATE connections
    SET status     = 'disconnected',
        updated_at = now()
    WHERE connections.id = $1
      AND connections.user_id = $2
      AND connections.status <> 'disconnected'
    RETURNING connections.id
),
paused AS (
    UPDATE campaigns
    SET status     = 'paused',
        updated_at = now()
    WHERE connection_id IN (SELECT id FROM target)
      AND status IN ('draft', 'scheduled', 'sending')
    RETURNING id
)
SELECT EXISTS (SELECT 1 FROM target) AS changed,
       (SELECT count(*) FROM paused)::bigint AS paused_campaigns
`

type DisconnectOwnedConnectionAndPauseCampaignsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type DisconnectOwnedConnectionAndPauseCampaignsRow struct {
	Changed         bool  `json:"changed"`
	PausedCampaigns int64 `json:"paused_campaigns"`
}

// Marks a connection disconnected and pauses everything it was sending.
//
// The same thing happens when Meta reports the customer removed access, so the
// rule lives in one place: a disconnected connection must never keep a campaign
// in a state that would try to send from it. Pausing only draft, scheduled and
// sending campaigns leaves finished history alone.
//
// `changed` is false when the connection was already disconnected, which is how
// the handler distinguishes a no-op retry from a real disconnect.
func (q *Queries) DisconnectOwnedConnectionAndPauseCampaigns(ctx context.Context, arg DisconnectOwnedConnectionAndPauseCampaignsParams) (DisconnectOwnedConnectionAndPauseCampaignsRow, error) {
	row := q.db.QueryRow(ctx, disconnectOwnedConnectionAndPauseCampaigns, arg.ID, arg.UserID)
	var i DisconnectOwnedConnectionAndPauseCampaignsRow
	err := row.Scan(&i.Changed, &i.PausedCampaigns)
	return i, err
}

const getConnectionByIDForUser = `-- name: GetConnectionByIDForUser :one
SELECT id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
FROM connections
WHERE id = $1
  AND user_id = $2
`

type GetConnectionByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Scoped by user_id on purpose: a connection id from the URL is untrusted, so
// the ownership check happens in the query rather than in the handler.
func (q *Queries) GetConnectionByIDForUser(ctx context.Context, arg GetConnectionByIDForUserParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByIDForUser, arg.ID, arg.UserID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessagingAccountID,
		&i.WaacID,
		&i.PhoneNumberID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.AccessTokenEncrypted,
		&i.TokenExpiresAt,
		&i.QualityRating,
		&i.MessagingLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingConnectionByUserAndWABA = `-- name: GetPendingConnectionByUserAndWABA :one
SELECT id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
FROM connections
WHERE user_id = $1
  AND messaging_account_id = $2
  AND phone_number_id IS NULL
`

type GetPendingConnectionByUserAndWABAParams struct {
	UserID             uuid.UUID `json:"user_id"`
	MessagingAccountID string    `json:"messaging_account_id"`
}

// Used when a signup returns an account with no phone numbers, to tell a first
// onboarding apart from a reconnect that lost a number.
//
// Scoped to rows with no phone number: once an account has numbers, it has one
// row per number and none of them are pending.
func (q *Queries) GetPendingConnectionByUserAndWABA(ctx context.Context, arg GetPendingConnectionByUserAndWABAParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getPendingConnectionByUserAndWABA, arg.UserID, arg.MessagingAccountID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessagingAccountID,
		&i.WaacID,
		&i.PhoneNumberID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.AccessTokenEncrypted,
		&i.TokenExpiresAt,
		&i.QualityRating,
		&i.MessagingLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsByUser = `-- name: ListConnectionsByUser :many
SELECT id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
FROM connections
WHERE user_id = $1
ORDER BY created_at DESC
`

// Every connection the signed-in user owns, newest first.
func (q *Queries) ListConnectionsByUser(ctx context.Context, userID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessagingAccountID,
			&i.WaacID,
			&i.PhoneNumberID,
			&i.PhoneNumber,
			&i.DisplayName,
			&i.AccessTokenEncrypted,
			&i.TokenExpiresAt,
			&i.QualityRating,
			&i.MessagingLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :one
INSERT INTO connections (
    user_id,
    messaging_account_id,
    waac_id,
    phone_number_id,
    phone_number,
    display_name,
    access_token_encrypted,
    token_expires_at,
    quality_rating,
    messaging_limit,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::connection_status
)
ON CONFLICT (user_id, phone_number_id) DO UPDATE
SET waac_id               = EXCLUDED.waac_id,
    phone_number_id       = EXCLUDED.phone_number_id,
    phone_number          = EXCLUDED.phone_number,
    display_name          = EXCLUDED.display_name,
    access_token_encrypted = EXCLUDED.access_token_encrypted,
    token_expires_at      = EXCLUDED.token_expires_at,
    quality_rating        = EXCLUDED.quality_rating,
    messaging_limit       = EXCLUDED.messaging_limit,
    status                = EXCLUDED.status,
    updated_at            = now()
RETURNING id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
`

type UpsertConnectionParams struct {
	UserID               uuid.UUID        `json:"user_id"`
	MessagingAccountID   string           `json:"messaging_account_id"`
	WaacID               *string          `json:"waac_id"`
	PhoneNumberID        *string          `json:"phone_number_id"`
	PhoneNumber          *string          `json:"phone_number"`
	DisplayName          string           `json:"display_name"`
	AccessTokenEncrypted []byte           `json:"access_token_encrypted"`
	TokenExpiresAt       time.Time        `json:"token_expires_at"`
	QualityRating        string           `json:"quality_rating"`
	MessagingLimit       int32            `json:"messaging_limit"`
	Status               ConnectionStatus `json:"status"`
}

// Stores one phone number as a connection.
//
// A WhatsApp Business Account can own several numbers, so the conflict target is
// the phone number rather than the account: reconnecting updates the row for
// that number, and a second number on the same account becomes a second row
// instead of overwriting the first.
//
// A conflict on the global phone_number_id index is deliberately not handled
// here: that index exists so one WhatsApp number can never belong to two
// tenants, and a violation is a real error the handler turns into a 409.
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, upsertConnection,
		arg.UserID,
		arg.MessagingAccountID,
		arg.WaacID,
		arg.PhoneNumberID,
		arg.PhoneNumber,
		arg.DisplayName,
		arg.AccessTokenEncrypted,
		arg.TokenExpiresAt,
		arg.QualityRating,
		arg.MessagingLimit,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessagingAccountID,
		&i.WaacID,
		&i.PhoneNumberID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.AccessTokenEncrypted,
		&i.TokenExpiresAt,
		&i.QualityRating,
		&i.MessagingLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingConnection = `-- name: UpsertPendingConnection :one
INSERT INTO connections (
    user_id,
    messaging_account_id,
    waac_id,
    access_token_encrypted,
    token_expires_at,
    quality_rating,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'UNKNOWN',
    $6::connection_status
)
ON CONFLICT (user_id, messaging_account_id) WHERE phone_number_id IS NULL DO UPDATE
SET waac_id                = EXCLUDED.waac_id,
    access_token_encrypted = EXCLUDED.access_token_encrypted,
    token_expires_at       = EXCLUDED.token_expires_at,
    quality_rating         = EXCLUDED.quality_rating,
    status                 = EXCLUDED.status,
    updated_at             = now()
RETURNING id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
`

type UpsertPendingConnectionParams struct {
	UserID               uuid.UUID        `json:"user_id"`
	MessagingAccountID   string           `json:"messaging_account_id"`
	WaacID               *string          `json:"waac_id"`
	AccessTokenEncrypted []byte           `json:"access_token_encrypted"`
	TokenExpiresAt       time.Time        `json:"token_expires_at"`
	Status               ConnectionStatus `json:"status"`
}

// Stores an account that has no phone number yet, as Embedded Signup v4 allows.
//
// Keyed on the account because there is no number to key on. The partial unique
// index behind it is what stops a customer pressing the signup button twice
// from collecting a duplicate pending row.
//
// Reconnecting brings a new token and expiry, so those columns are updated too.
func (q *Queries) UpsertPendingConnection(ctx context.Context, arg UpsertPendingConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, upsertPendingConnection,
		arg.UserID,
		arg.MessagingAccountID,
		arg.WaacID,
		arg.AccessTokenEncrypted,
		arg.TokenExpiresAt,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessagingAccountID,
		&i.WaacID,
		&i.PhoneNumberID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.AccessTokenEncrypted,
		&i.TokenExpiresAt,
		&i.QualityRating,
		&i.MessagingLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
