// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CampaignStatus string

const (
	CampaignStatusDraft     CampaignStatus = "draft"
	CampaignStatusScheduled CampaignStatus = "scheduled"
	CampaignStatusSending   CampaignStatus = "sending"
	CampaignStatusPaused    CampaignStatus = "paused"
	CampaignStatusCompleted CampaignStatus = "completed"
	CampaignStatusFailed    CampaignStatus = "failed"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type ConnectionStatus string

const (
	ConnectionStatusActive       ConnectionStatus = "active"
	ConnectionStatusDisconnected ConnectionStatus = "disconnected"
	ConnectionStatusTokenExpired ConnectionStatus = "token_expired"
	ConnectionStatusPendingPhone ConnectionStatus = "pending_phone"
)

func (e *ConnectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionStatus(s)
	case string:
		*e = ConnectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionStatus: %T", src)
	}
	return nil
}

type NullConnectionStatus struct {
	ConnectionStatus ConnectionStatus `json:"connection_status"`
	Valid            bool             `json:"valid"` // Valid is true if ConnectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionStatus), nil
}

type MessageStatus string

const (
	MessageStatusQueued    MessageStatus = "queued"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusSkipped   MessageStatus = "skipped"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus `json:"message_status"`
	Valid         bool          `json:"valid"` // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type ScheduleKind string

const (
	ScheduleKindNow       ScheduleKind = "now"
	ScheduleKindAt        ScheduleKind = "at"
	ScheduleKindRecurring ScheduleKind = "recurring"
)

func (e *ScheduleKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleKind(s)
	case string:
		*e = ScheduleKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleKind: %T", src)
	}
	return nil
}

type NullScheduleKind struct {
	ScheduleKind ScheduleKind `json:"schedule_kind"`
	Valid        bool         `json:"valid"` // Valid is true if ScheduleKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleKind) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleKind), nil
}

type TemplateCategory string

const (
	TemplateCategoryUTILITY        TemplateCategory = "UTILITY"
	TemplateCategoryMARKETING      TemplateCategory = "MARKETING"
	TemplateCategoryAUTHENTICATION TemplateCategory = "AUTHENTICATION"
)

func (e *TemplateCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateCategory(s)
	case string:
		*e = TemplateCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateCategory: %T", src)
	}
	return nil
}

type NullTemplateCategory struct {
	TemplateCategory TemplateCategory `json:"template_category"`
	Valid            bool             `json:"valid"` // Valid is true if TemplateCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateCategory), nil
}

type TemplateStatus string

const (
	TemplateStatusDraft    TemplateStatus = "draft"
	TemplateStatusPending  TemplateStatus = "pending"
	TemplateStatusApproved TemplateStatus = "approved"
	TemplateStatusRejected TemplateStatus = "rejected"
	TemplateStatusPaused   TemplateStatus = "paused"
)

func (e *TemplateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateStatus(s)
	case string:
		*e = TemplateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateStatus: %T", src)
	}
	return nil
}

type NullTemplateStatus struct {
	TemplateStatus TemplateStatus `json:"template_status"`
	Valid          bool           `json:"valid"` // Valid is true if TemplateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateStatus), nil
}

type UserPlan string

const (
	UserPlanFree     UserPlan = "free"
	UserPlanStarter  UserPlan = "starter"
	UserPlanPro      UserPlan = "pro"
	UserPlanBusiness UserPlan = "business"
)

func (e *UserPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPlan(s)
	case string:
		*e = UserPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPlan: %T", src)
	}
	return nil
}

type NullUserPlan struct {
	UserPlan UserPlan `json:"user_plan"`
	Valid    bool     `json:"valid"` // Valid is true if UserPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPlan) Scan(value interface{}) error {
	if value == nil {
		ns.UserPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPlan), nil
}

type AuditLog struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	EntityID  *string     `json:"entity_id"`
	Meta      []byte      `json:"meta"`
	Ip        *netip.Addr `json:"ip"`
	CreatedAt time.Time   `json:"created_at"`
}

type Campaign struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	ConnectionID       uuid.UUID      `json:"connection_id"`
	TemplateID         uuid.UUID      `json:"template_id"`
	Name               string         `json:"name"`
	ScheduleKind       ScheduleKind   `json:"schedule_kind"`
	Schedule           []byte         `json:"schedule"`
	Status             CampaignStatus `json:"status"`
	RiverPeriodicJobID *string        `json:"river_periodic_job_id"`
	TotalCount         int32          `json:"total_count"`
	SentCount          int32          `json:"sent_count"`
	DeliveredCount     int32          `json:"delivered_count"`
	ReadCount          int32          `json:"read_count"`
	FailedCount        int32          `json:"failed_count"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Connection struct {
	ID                   uuid.UUID        `json:"id"`
	UserID               uuid.UUID        `json:"user_id"`
	MessagingAccountID   string           `json:"messaging_account_id"`
	WaacID               *string          `json:"waac_id"`
	PhoneNumberID        *string          `json:"phone_number_id"`
	PhoneNumber          *string          `json:"phone_number"`
	DisplayName          string           `json:"display_name"`
	AccessTokenEncrypted []byte           `json:"access_token_encrypted"`
	TokenExpiresAt       time.Time        `json:"token_expires_at"`
	QualityRating        string           `json:"quality_rating"`
	MessagingLimit       int32            `json:"messaging_limit"`
	Status               ConnectionStatus `json:"status"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
}

type Contact struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Phone     string             `json:"phone"`
	Name      string             `json:"name"`
	OptIn     bool               `json:"opt_in"`
	OptInAt   pgtype.Timestamptz `json:"opt_in_at"`
	Variables []byte             `json:"variables"`
	CreatedAt time.Time          `json:"created_at"`
}

type MessageLog struct {
	ID           uuid.UUID          `json:"id"`
	CampaignID   uuid.UUID          `json:"campaign_id"`
	ContactID    pgtype.UUID        `json:"contact_id"`
	Wamid        *string            `json:"wamid"`
	Status       MessageStatus      `json:"status"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	SkipReason   *string            `json:"skip_reason"`
	QueuedAt     time.Time          `json:"queued_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type Template struct {
	ID              uuid.UUID        `json:"id"`
	ConnectionID    uuid.UUID        `json:"connection_id"`
	MetaTemplateID  *string          `json:"meta_template_id"`
	Name            string           `json:"name"`
	Category        TemplateCategory `json:"category"`
	Language        string           `json:"language"`
	Components      []byte           `json:"components"`
	Variables       []string         `json:"variables"`
	Status          TemplateStatus   `json:"status"`
	RejectionReason *string          `json:"rejection_reason"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Plan         UserPlan  `json:"plan"`
	CreatedAt    time.Time `json:"created_at"`
}
