// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMessageStatus = `-- name: AdvanceMessageStatus :one
UPDATE message_logs AS m
SET status = CASE
        WHEN current.advances THEN $1
        ELSE m.status
    END,
    sent_at = CASE
        WHEN current.advances AND $1::message_status = 'sent' THEN COALESCE(m.sent_at, $2)
        ELSE m.sent_at
    END,
    delivered_at = CASE
        WHEN current.advances AND $1::message_status = 'delivered' THEN COALESCE(m.delivered_at, $2)
        ELSE m.delivered_at
    END,
    read_at = CASE
        WHEN current.advances AND $1::message_status = 'read' THEN COALESCE(m.read_at, $2)
        ELSE m.read_at
    END,
    failed_at = CASE
        WHEN current.advances AND $1::message_status = 'failed' THEN COALESCE(m.failed_at, $2)
        ELSE m.failed_at
    END,
    -- Keep the first error: a redelivered failure carries the same code.
    error_code = CASE
        WHEN current.advances AND $1::message_status = 'failed' THEN COALESCE($3, m.error_code)
        ELSE m.error_code
    END,
    error_message = CASE
        WHEN current.advances AND $1::message_status = 'failed' THEN COALESCE($4, m.error_message)
        ELSE m.error_message
    END
FROM (
    -- The transition matrix, in one place. Meta redelivers webhooks and
    -- delivery statuses can arrive out of order, so only forward moves are
    -- allowed: a redelivered "delivered" after "read" is ignored, and "failed"
    -- is terminal because it wins over every delivery state.
    SELECT id,
           CASE
               WHEN $1::message_status = status THEN false
               WHEN status = 'queued'
                   AND $1::message_status IN ('sent', 'delivered', 'read', 'failed') THEN true
               WHEN status = 'sent'
                   AND $1::message_status IN ('delivered', 'read', 'failed') THEN true
               WHEN status = 'delivered'
                   AND $1::message_status IN ('read', 'failed') THEN true
               WHEN status = 'read'
                   AND $1::message_status = 'failed' THEN true
               ELSE false
           END AS advances
    FROM message_logs
    WHERE message_logs.wamid = $5
) AS current
WHERE m.id = current.id
RETURNING m.id, m.campaign_id, m.contact_id, m.wamid, m.status, m.error_code, m.error_message, m.skip_reason, m.queued_at, m.sent_at, m.delivered_at, m.read_at, m.failed_at
`

type AdvanceMessageStatusParams struct {
	Status       MessageStatus      `json:"status"`
	At           pgtype.Timestamptz `json:"at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	Wamid        *string            `json:"wamid"`
}

// Records a delivery status transition on the message row identified by wamid.
//
// Meta redelivers webhooks, and delivery statuses can arrive out of order, so
// a transition must never move a message backwards.
//
// The guard is computed once, in the subquery, and gates the status *and* every
// timestamp. A transition that is not applied therefore has no effect at all,
// which is what keeps failed_at honest for analytics.
//
// A message we have never seen returns no row: :one reports pgx.ErrNoRows and
// the handler answers 200, because a non-2xx would make Meta redeliver forever.
func (q *Queries) AdvanceMessageStatus(ctx context.Context, arg AdvanceMessageStatusParams) (MessageLog, error) {
	row := q.db.QueryRow(ctx, advanceMessageStatus,
		arg.Status,
		arg.At,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Wamid,
	)
	var i MessageLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.SkipReason,
		&i.QueuedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
	)
	return i, err
}

const disconnectConnectionAndPauseCampaigns = `-- name: DisconnectConnectionAndPauseCampaigns :execrows
WITH target AS (
    UPDATE connections
    SET status = 'disconnected',
        updated_at = now()
    WHERE ($1::text = '' OR phone_number_id = $1::text)
      AND ($2::text = '' OR messaging_account_id = $2::text)
      AND status <> 'disconnected'
    RETURNING id
)
UPDATE campaigns
SET status = 'paused',
    updated_at = now()
WHERE connection_id IN (SELECT id FROM target)
  AND status IN ('draft', 'scheduled', 'sending')
`

type DisconnectConnectionAndPauseCampaignsParams struct {
	PhoneNumberID      string `json:"phone_number_id"`
	MessagingAccountID string `json:"messaging_account_id"`
}

// Marks a connection disconnected and pauses everything it was sending.
//
// account_update arrives when a business removes the app's access. The payload
// carries a phone number id, a WABA id, or both, so an empty argument means
// "do not match on this column". Re-delivery is a no-op: a connection that is
// already disconnected returns no rows, so its campaigns are not touched again.
func (q *Queries) DisconnectConnectionAndPauseCampaigns(ctx context.Context, arg DisconnectConnectionAndPauseCampaignsParams) (int64, error) {
	result, err := q.db.Exec(ctx, disconnectConnectionAndPauseCampaigns, arg.PhoneNumberID, arg.MessagingAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectionByPhoneNumberID = `-- name: GetConnectionByPhoneNumberID :one
SELECT id, user_id, messaging_account_id, waac_id, phone_number_id, phone_number, display_name, access_token_encrypted, token_expires_at, quality_rating, messaging_limit, status, created_at, updated_at
FROM connections
WHERE phone_number_id = $1
`

func (q *Queries) GetConnectionByPhoneNumberID(ctx context.Context, phoneNumberID *string) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByPhoneNumberID, phoneNumberID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessagingAccountID,
		&i.WaacID,
		&i.PhoneNumberID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.AccessTokenEncrypted,
		&i.TokenExpiresAt,
		&i.QualityRating,
		&i.MessagingLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageLogByWamid = `-- name: GetMessageLogByWamid :one
SELECT id, campaign_id, contact_id, wamid, status, error_code, error_message, skip_reason, queued_at, sent_at, delivered_at, read_at, failed_at
FROM message_logs
WHERE wamid = $1
`

func (q *Queries) GetMessageLogByWamid(ctx context.Context, wamid *string) (MessageLog, error) {
	row := q.db.QueryRow(ctx, getMessageLogByWamid, wamid)
	var i MessageLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.SkipReason,
		&i.QueuedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
	)
	return i, err
}

const updateTemplateReviewStatus = `-- name: UpdateTemplateReviewStatus :execrows
UPDATE templates
SET status = $1::template_status,
    rejection_reason = $2
WHERE meta_template_id = $3
`

type UpdateTemplateReviewStatusParams struct {
	Status          TemplateStatus `json:"status"`
	RejectionReason *string        `json:"rejection_reason"`
	MetaTemplateID  *string        `json:"meta_template_id"`
}

// Applies a template review status from Meta. The reason doubles as the
// rejection reason shown in the UI.
func (q *Queries) UpdateTemplateReviewStatus(ctx context.Context, arg UpdateTemplateReviewStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTemplateReviewStatus, arg.Status, arg.RejectionReason, arg.MetaTemplateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
